### ISSUE TITLE
os.environ key error

### ISSUE THREAD

**Issue by himchanjung** [stanfordjournalism/stanford-progj-2020#14]
```
def main():
    api_key = os.environ["PROPUBLICA_API_KEY"]
```

When I use this code to insert my api key, I get the below message.  

```
Traceback (most recent call last):
  File "senate_rank_breakers.py", line 121, in <module>
    main()
  File "senate_rank_breakers.py", line 32, in main
    api_key = os.environ["fAnG9NgWQHUmzdplFGAb5HWcepaBnO9ZIgExKspv"]
  File "/home/jwongi/.pyenv/versions/3.7.6/lib/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'fAnG9NgWQHUmzdplFGAb5HWcepaBnO9ZIgExKspv'
```
But when I took away os.environ and just put my api key, the code ran without problem.
Can I run the code without os.environ? Would it cause any problem if someone else runs the code in different setting (i.e. anyone else's computer?)

**Comment by zstumgoren** [comment]
@himchanjung the os.environ['PROPUBLICA_API_KEY'] looks up the environment variable of that name (PROPUBLICA_API_KEY). It appears you tried to update this lookup by using your actual API key. 

I'll contact you offline with a recommended reading for clarity. Meantime, I'll delete this ticket so you're API key is not exposed publicly.

**Comment by zstumgoren** [comment]
@himchanjung I don't appear to have permissions to delete the ticket. Can you please delete?

**Comment by himchanjung** [comment]
Thanks for your response. It seems that only the administrator of this repo can delete this; for now, I edited the original post and took out my api key from the string.
