### ISSUE TITLE
Trouble installing Ubuntu 16.04 using Oracle VirtualBox

### ISSUE THREAD

**Issue by himchanjung** [stanfordjournalism/stanford-progj-2020#6]
I followed the technical setup [instructions](https://brb.nci.nih.gov/seqtools/installUbuntu.html) but got the below message. Anyone who's encountering a similar problem?

The virtual machine 'ubuntu1604' has terminated unexpectedly during startup with exit code -1073741819 (0xc0000005).

Result Code: | E_FAIL (0x80004005)

**Comment by zstumgoren** [comment]
@himchanjung I haven't seen this before, but can you review this [post](https://technow.me/fix-virtual-machine-has-terminated-unexpectedly-during-startup-with-exit-code-1-0x1/) and see if any of the suggestions work.

Also, you appear to be installing an older version of Ubuntu. Could you install Ubuntu 18.04 LTS from [here](https://ubuntu.com/download/desktop)?

**Comment by himchanjung** [comment]
@zstumgoren I've tried the instructions but wasn't able to fix the problem. 
I'll use the mac at the classroom for today's session. I'll continue looking for the solutions.

**Comment by himchanjung** [comment]
Resolved using VMWare workstation.

For those who want to use Ubuntu on Windows, I recommend using VMware [workstation 15](https://www.vmware.com/products/workstation-player.html) instead of Oracle VirtualBox.

VMware Workstation Player 15 is free for non-commercial use. You can follow this [video instruction](https://www.youtube.com/watch?v=QCSyqrgM0sU) to install Ubuntu.
