### ISSUE TITLE
How to make Python3 primary system version?

### ISSUE THREAD

**Issue by vochavillo** [stanfordjournalism/stanford-progj-2020#7]
On Mac Sierra, after brew installing per Hitchhiker's docs, `python` still points to python2 executable. We need `python` to point to Python 3.

```
==> python
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
```

**Comment by zstumgoren** [comment]
@vochavillo Were you able to resolve this issue based on what we discussed in class? Here are the steps to try, per the [Hitchhiker's Guide to Python](https://docs.python-guide.org/starting/install3/osx/)

```
echo '"export PATH="/usr/local/opt/python/libexec/bin:$PATH"' >> ~/.bash_profile
# Open a new shell
python --version

# If the above fails:
echo '"export PATH="/usr/local/opt/python/libexec/bin:$PATH"' >> ~/.profile
# Open new shell
python --version
```
If the above doesn't work, open the `.bash_profile` and `.profile` files and replace the export line with this: `export PATH=/usr/local/bin:/usr/local/sbin:$PATH`. Each time, open a new shell and type`python --version`.

**Comment by vochavillo** [comment]
@zstumgoren - It's still showing python 2 as my primary...

**Comment by zstumgoren** [comment]
Fixed this by removing stray quote mark from export in `~/.bash_profile`
