### ISSUE TITLE
running python configure_system.py (DataKit setup)

### ISSUE THREAD

**Issue by DiPierro** [stanfordjournalism/stanford-progj-2020#8]
I'm having trouble running python configure_system.py.

I've run the following steps with no issues:

```
curl -s https://raw.githubusercontent.com/stanfordjournalism/cookiecutter-stanford-progj/master/requirements.txt | xargs pip install

curl -O https://raw.githubusercontent.com/stanfordjournalism/stanford-dj-vm/master/configure_system.py
```

But when I get to the final step, I get this error:

```
  File "configure_system.py", line 1
    404: Not Found
                 ^
SyntaxError: invalid syntax
```
I've got python installed. How can I diagnose the error?

**Comment by zstumgoren** [comment]
@DiPierro Did you run `python python configure_system.py`? If so, could you paste the full stack trace?

**Comment by DiPierro** [comment]
Gosh, I think I might have simply had a typo the first few times I ran curl. 

configure_system.py worked when I re-ran it just now.

**Comment by zstumgoren** [comment]
@DiPierro glad you got it sorted! Shout back if you run into any other issues. Would be great to hear about snags before the whole class does the install today in class!
